### PR TITLE
Support custom package name

### PR DESCRIPTION
**Pull request by tdevelioglu**
Add support for setting a custom package name.

### CODE REVIEW

**Comment by mcanevet** [comment]
@tdevelioglu official puppetserver package name is the same on all supported platforms. Are you rebuilding your own packages?

**Comment by tdevelioglu** [comment]
@mcanevet you are correct. In this case we rebuild because we need modified dependencies.

**Comment by mcanevet** [comment]
@tdevelioglu ok. Could you please squash your commits?

**Comment by tdevelioglu** [comment]
@mcanevet sure, done

**Comment by mcanevet** [comment]
@tdevelioglu thanks

**Pull request merged**
